table _Measures
	lineageTag: 6c02cd65-f3f9-44a3-863e-bb5796a70c1c

	measure 'Number of Reservations' = COUNTROWS(Reservations)
		formatString: #,0
		lineageTag: 7716a1a4-aca0-463b-80ce-d4fa18c5dbe5

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WSlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

