table Org
	lineageTag: c26804a7-c70d-48c7-b5a1-cf7675ddc7f0

	column level1
		dataType: string
		lineageTag: d9f62f19-e794-4f4b-a020-7043fd13b66c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: level1

		annotation SummarizationSetBy = Automatic

	column person
		dataType: string
		lineageTag: ef107f57-9937-41cc-8125-9c64a8f9b2f2
		summarizeBy: none
		sourceColumn: person

		annotation SummarizationSetBy = Automatic

	column kpi
		dataType: int64
		formatString: 0
		lineageTag: c5640ca3-963c-4203-bb08-225cdae3efa3
		summarizeBy: none
		sourceColumn: kpi

		annotation SummarizationSetBy = User

	column level2
		dataType: string
		lineageTag: bdea7b59-578a-413d-b4d0-a2644d3678e2
		summarizeBy: none
		sourceColumn: level2

		annotation SummarizationSetBy = Automatic

	column level3
		dataType: string
		lineageTag: 0e8ebdd8-4dde-48ab-b26f-3050f33d18ea
		summarizeBy: none
		sourceColumn: level3

		annotation SummarizationSetBy = Automatic

	column level4
		dataType: string
		lineageTag: 28d78a67-ff37-4f7f-baad-6bb6dfa4bbee
		summarizeBy: none
		sourceColumn: level4

		annotation SummarizationSetBy = Automatic

	column level5
		dataType: string
		lineageTag: e2d16453-5262-4c98-b688-ee609d1aaf02
		summarizeBy: none
		sourceColumn: level5

		annotation SummarizationSetBy = Automatic

	partition Org = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("nVfbjtowEP0Va5+rquWysI+BZe/ZIrLVqq36MEmmxMWxkeOwzX5aX/tjHQdCQzCQrYQQAZ/j8cyZM+bbtzMvSvHs3ZkPv5in08xoJef0POjT27/X93fblZcvUEhkIy4EV4a+GH6gt0elTcK8FDWPwImbqRC1YeP3bAw65VECKOjrvgv9WXKDMQsMGMz2qSbxC+iYXanMoKbn8zYcnkZgHxtMdyrmyG64MErSY+dNRA8qAsOVpIca5RWXAgrmLRIDNriP/8fZ2Q0T2ReVl5Xp9v6Lr1vnu0al50jLcZmgtIBhvy1rp5HCe+Qa2E0+T8o1nTcRuVPohXwOXDBPCLRl6bVOYbcRXLBEGaFmU43ZusTDi7dwueMLImUMG+E8T+npYtCWsddsCQwxioCNQMtyVXut9A5q5Sss2I1a2o/91rXYoduRykQgSKWZZxa8VEqndQJ7JxLoR+QEJilsVVrnsN/I4TgBLTBjAUo4JJUxSIgrV6phfYh5RrFN1QsKa0Y919m2aKeDBJHdn04zIxLbnkcDOOEdT2SqBXuutOr0xiNcOzp4tgYNKfO5KLM3OE3WbO3bDEJKDLBPgq/KNielhiqzgAtL9+A9eb7T7X0+z1GwK9TaAiuTrgA+/uKR2odd55mBlWI+CYPkxq5VWgbvBteS2KCBUHOKHIlARiBWJUn3OEnz9IH6wcEOqxWIxK48Pz+Kb3rPjBQpaahC/lOxKZdGVR1ecXhkwpLO6ZDmJOWkhDW4UoILdjAFm9ohmWiKvKxxd1AjGWl45WJ/47s/v2mubwtXg18Ma/BxHrqijnMazMB8FMpmLlaZqppyi0xIkPtQLwVJyLLgW701K19hnZ24kdwUK8U5t3UK/RIkp4gfeArsksPWip3gZp0ndAtZUaUDLlakl1wmZbJ7x/Du9p/IV2VbTCvyM5W/QtW2p3l2Wv+Br0i5MxVrm5Ks1rXddmxdR16rgw3bUfTqFFOMtVofaZ2m9qH0d0QieJYQxXqqV+qY+BPPaUI3UMQo/90TO7XVn+8d2odIhSzIU/LHrQY266800J77mGmiaIqze76+nNUQtwZE4dhEUTKfExptCUJc9XYDc7CtZ3lYkE6NKdM1qEGDJXC5v52vaAzQFZcMVWDRSEKFObidJ34QeIYYN5K9h2y21CMYsLV6JuMrk19eRrypN3aWagyUc6IpE9NY7dFQ0EDDbB8WqGVCUh/l0WJzuhruEV/YVwRBxrKP/JLTlZqKxp4yldvK1YCkRpcnk0XRPagoymt9r7b+Vsau4Dy95Ib0vu6bvgPg9DG60dDPCzpVAsYA/VHSRemExwjchnIHBdDdF8LEHnHQimDHSQKgsZUlNhQdr+Dn2eafwkkWcpDvfwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [level1 = _t, person = _t, kpi = _t, level2 = _t, level3 = _t, level4 = _t, level5 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"level1", type text}, {"person", type text}, {"kpi", Int64.Type}, {"level2", type text}, {"level3", type text}, {"level4", type text}, {"level5", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

